language: go

go:
  - 1.5

addons:
  hosts:
    - le.wtf
  apt:
    packages:
      - lsb-release
      - python-dev
      - python-virtualenv
      - gcc
      - libaugeas0
      - libssl-dev
      - libffi-dev
      - ca-certificates
      - rsyslog
  mariadb: "10.0"

sudo: false

services:
  - rabbitmq
  - mysql

matrix:
  fast_finish: true

before_install:
  # Boulder consists of multiple Go packages, which
  # refer to each other by their absolute GitHub path,
  # e.g. github.com/letsencrypt/boulder/analysis. That means, by default, if
  # someone forks the repo, Travis won't pass on their own repo. To fix that,
  # we add a symlink.
  - python --version
  - mkdir -p $TRAVIS_BUILD_DIR $GOPATH/src/github.com/letsencrypt
  - test ! -d $GOPATH/src/github.com/letsencrypt/boulder && ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/letsencrypt/boulder || true
  - git clone -b mock-2.6 https://www.github.com/kuba/letsencrypt.git "$LETSENCRYPT_PATH"
  - cd "$LETSENCRYPT_PATH"
  - virtualenv --no-site-packages -p python2 ./venv
  - travis_retry ./venv/bin/pip install -U setuptools  # #681
  - ./venv/bin/pip install mock
  - ./venv/bin/pip freeze
  - ./venv/bin/pip list
  - ./venv/bin/python -c "import mock"
  - "cd -"

env:
  global:
    - LETSENCRYPT_PATH=/tmp/letsencrypt
  matrix:
    - SKIP_INTEGRATION_TESTS=1
    - SKIP_UNIT_TESTS=1

script:
  - echo OK
